FROM python:3.6

ENV SHELL /bin/bash

WORKDIR /vgg16_model

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
	
COPY model model

COPY load_and_test_model.py load_and_test_model.py